### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by jas4711** [Yubico/yubikey-personalization-gui#50]
Doesn't seem to build on some platforms -- new test, or new regression?

https://buildd.debian.org/status/package.php?p=yubikey-personalization-gui&suite=unstable

**Comment by klali** [comment]
this might've been fixed by d9f7f62d9cf8e01de32fdd0565da35e83d3f9d6c

**Comment by klali** [comment]
Yes, fixed in that revision.
