### ISSUE TITLE
[AZERTY] - layout SHIFT issue with HOTP

### ISSUE THREAD

**Issue by TomAtYubico** [Yubico/yubikey-personalization-gui#54]
Setting the option "use numeric keypad" requires the user to press the SHIFT button pressed to emit proper AZERTY layout using number in the top bar rather than the numeric keypad.

_Version 3.1.18_
_Library Version 1.16.2_

* The NEO Firmware Version: 3.4.3
* The NEO-n  Firmware Version: 3.3.7

**Comment by klali** [comment]
that option is only available in the 2.x line of firmware.
