### ISSUE TITLE
Memory access error 

### ISSUE THREAD

**Issue by katodev** [Yubico/yubikey-personalization-gui#56]
I got an memory access error when I choose the DE or US keyboard layout or press the exit button. In both cases the GUI exits.

Version 3.1.22
Lib 1.17.2
openSUSE 13.2  32Bit
Build options:
qmake-qt5 'CONFIG+=nosilent c++11' 'QMAKE_CXXFLAGS=-fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fvisibility=hidden -fvisibility-inlines-hidden'
make -j8

**Comment by klali** [comment]
Thanks for reporting this!

I'm unable to reproduce the crash on the exit button. If you can get a backtrace of that with gdb I'm happy to dig deeper.
I'm commiting a fix for the crash on keyboard layout shortly.

**Comment by klali** [comment]
Nevermind about the exit crash, seems to be the same cause.

**Comment by katodev** [comment]
The error with the exit button is gone with this patch too. !?!?!

**Comment by klali** [comment]
Yes, it was the same bug with scanedit not being initialized, hitting from the destructor or form when it tried to clear it. It'd be great if you could test this fix from source, there will be a new version in a couple of days..

**Comment by katodev** [comment]
Yes, it works. 
I noticed not all characters are supported with the german layout. Can't handle the Yubikey with the 'AltGr' key?
For information: The Yubikey gets support in the next OpenSUSE Leap 42.1 release.

**Comment by klali** [comment]
Yes, the only modifier key that can be handled is shift.
I might still have missed some characters in the mapping for german since I did that without a german keyboard at hand.
