### ISSUE TITLE
No signatures/hashes listed on https://www.yubico.com/support/downloads/

### ISSUE THREAD

**Issue by edmorley** [Yubico/yubikey-personalization-gui#57]
I needed to download the personalisation tool, so ended up on https://www.yubico.com/products/services-software/personalization-tools/use/ which links to https://www.yubico.com/support/downloads/

The download page links to the win32 binaries, but doesn't display (or link to) signatures and/or SHA1/SHA256 hashes of any of the binaries on that page, which I found pretty surprising.

Please can you add such links? (Ideally not just for the personalisation tool, but many of the downloads on that page)

Thanks :-)

**Comment by dainnilsson** [comment]
We provide OpenPGP signatures for source packages, etc. on https://developers.yubico.com, for example: https://developers.yubico.com/yubikey-personalization-gui/Releases/

We don't always do this for .exe or .pkg files, as they are instead digitally signed using the OSes native code signing features.

**Comment by edmorley** [comment]
I looked pretty hard and didn't find that page.
Could you advertise it on https://www.yubico.com/support/downloads/ ?

**Comment by dainnilsson** [comment]
I'll forward your request to the relevant department.

**Comment by edmorley** [comment]
Thanks :-)

It's just a downloads page where some of the links are to WordPress upload directories (eg https://www.yubico.com/wp-content/uploads/2015/07/yubico-windows-auth.exe) doesn't exactly fill me with confidence.
