### ISSUE TITLE
Doesn't work with new U2F keys?

### ISSUE THREAD

**Issue by frioux** [Yubico/yubikey-personalization-gui#60]
The UI of this seems like it should allow reconfiguring U2F keys, given that it shows a U2F boolean on the main page.  But when I plugin my GH branded U2F yubikey it doesn't notice it at all...  Any idea what's wrong?

**Comment by kylemanna** [comment]
Seems like it should, but you need to use another tool:
https://github.com/Yubico/yubikey-neo-manager

I agree, I'd expect one tool to allow me to configure my Yubikey, but it seems fragmented with multiple apps and libraries.

**Comment by frioux** [comment]
Ah thanks @kylemanna.  For the most part I've found the yubikey ecosystem to be sensible, though this is their first departure from their relatively large original gui.  As long as there is a tool that will let me reset my key I'm happy.

**Comment by frioux** [comment]
Actually, just installed that app and it detects the device but then claims that it is not supported. :cry:

**Comment by SueHeim** [comment]
If you are using the new GitHub special edition Octocat keys, those keys are U2F only. Those keys, as well as our Security Keys cannot be configured using the Personalization Tool. See https://www.yubico.com/faq/why-doesnt-the-yubikey-personalization-tool-recognize-my-security-key/.

**Comment by frioux** [comment]
That's really too bad; I'd like to be able to replace the internal keys.  Thanks for letting me know though!
