### ISSUE TITLE
Yubikey not recognized with OTP connection mode disabled

### ISSUE THREAD

**Issue by kasparsd** [Yubico/yubikey-personalization-gui#61]
I had disabled the OTP connection mode which made the Personalization Tool to not recognize the key.

![yubikey-not-inserted](https://cloud.githubusercontent.com/assets/169055/11335313/efbbb948-91e3-11e5-8693-13b7db8d1461.png)

I realize that without the OTP mode there is very little to configure but users might still expect it to be recognized.

**Comment by CJHarms** [comment]
Can confirm. After disabling OTP Mode on my YubiKey 4 it is no longer detected by the Personalization Tool.

**Comment by omrltfm** [comment]
how did you fix this?  My Yubikey 4 isn't being recognized by the Personalization tool.

**Comment by kasparsd** [comment]
@omrltfm You need to enable the OTP mode by clicking "Change connection mode".

**Comment by dagheyman** [comment]
This is by design. OTP mode need to be enabled for this tool to be able to recognise the device. Please note that [YubiKey Manager](https://developers.yubico.com/yubikey-manager-qt/) is able to recognise the device in all modes as well as perform the most common slot-based configuration tasks (when OTP is enabled).

**Comment by kasparsd** [comment]
@dagheyman However, it is confusing for the user that the tool can't find a Yubikey that's actually plugged in the computer. A better UX would be to tell the users to "enable the OTP mode" to start the personalization.

It checks the following NEO [device PIDs](https://github.com/Yubico/yubikey-personalization/blob/c3a673492ec2c05e7b77fc8b729f1f80894ac963/ykcore/ykcore.c#L84-L87) during `yk_open_first_key()` which calls `yk_open_key()`:

- NEO_OTP_PID
- NEO_OTP_CCID_PID
- NEO_OTP_U2F_PID
- NEO_OTP_U2F_CCID_PID

and all of them require OTP. Same with Yubikey 4 PIDs.

Could we introduce another method such as `yk_detect_key()` which checks for the presence of either PID?
