### ISSUE TITLE
Disabling Output Format "Enter" key doesn't work

### ISSUE THREAD

**Issue by Fryguy** [Yubico/yubikey-personalization-gui#65]
I'm not sure if this issue is an application or library issue, but when I un-click the "Enter" under Settings -> "Output Format" and do "Update Settings..." to write it to the YubiKey, it doesn't actually work.  Touching the YubiKey still sends a CR at the end of the string.  (This is particularly annoying for chat rooms where I might accidentally bump the key and send the random string by accident, which is why I want to disable the CR)

YubiKey Nano Firmware Version: 2.5.1
Application Version: 3.1.23
Library Version: 1.17.2
Mac OSX El Capitan 10.11.1

**Comment by klali** [comment]
I'm not able to reproduce this.

Can you try this with the commandline tool ykpersonalize (downloadable from https://developers.yubico.com/yubikey-personalization/Releases/) by running:
$ ykpersonalize -u -1 -oallow-update

and reporting back with what output that gives. (this will remove all updatable flags except allow-update).

**Comment by Fryguy** [comment]
```
05:09:12 ~/Downloads/ykpers-1.17.3-mac/bin ✓ ./ykpersonalize -u -1 -oallow-update
Firmware version 2.5.1 Touch level 2306 Program sequence 2

Configuration data to be updated in key configuration 1:

fixed: m:
uid: 000000000000
key: h:00000000000000000000000000000000
acc_code: h:000000000000
ticket_flags: APPEND_CR
config_flags:
extended_flags: ALLOW_UPDATE

Commit? (y/n) [n]: y
Yubikey core error: write error
```

exit code is 2

**Comment by dkunitsk** [comment]
I am getting this error also, and am unable to disable the CR. Is there any resolution to this?

**Comment by klali** [comment]
Sorry for missing the reply to this. You would typically get that error if the allow-update flag is not set on the current config.

Though it looks like to me like only your slot 2 is programmed? (touchlevel 2306 == 0x902, low 4-bits being 2 meaning CONFIG2_VALID is set, but not CONFIG1_VALID)

@dkunitsk hope this helps your as well, otherwise more information would be required.

**Comment by JohnTheodore** [comment]
I have the same question. I keep dumping text in slack and other random chat windows. The way I sit on my couch, I often knock the key. :(

How can I make it not hit enter when I hit the key?

ykpersonalize -u -1 -oallow-update
Firmware version 4.3.3 Touch level 522 Program sequence 2

Configuration data to be updated in key configuration 1:

fixed: m:
uid: 000000000000
key: h:00000000000000000000000000000000
acc_code: h:000000000000
ticket_flags: APPEND_CR
config_flags:
extended_flags: ALLOW_UPDATE

Commit? (y/n) [n]: y
Yubikey core error: write error


How can I tell if my slot 2 is programmed?

**Comment by klali** [comment]
update slot 1 and remove append-cr:
$ ykpersonalize -u -1 -oallow-update -o-append-cr

check if slot 2 is programmed:
$ ykinfo -2
