### ISSUE TITLE
Password entry field doesn't work (Mac)

### ISSUE THREAD

**Issue by peterkaminski** [Yubico/yubikey-personalization-gui#66]
When I run the YubiKey Personalization Tool, I select "Static Password" tab, then "Scan Code" button, then select the "Configuration Slot 2" radio button.  The text entry field to the right of "Password" in the "Password" section is non-responsive.  When I click on it, it doesn't get a blue outline like text entry fields in other tabs, there is no cursor in the box, and when I type keys or try to paste via Cmd-V or mouse, nothing happens.

The outcome is that I cannot set the static password for my YubiKey, because I cannot enter a password.

If I hit the Tab key in that tab, the blue highlight around the "Program Multiple YubiKeys" checkbox toggles on and off, but no other controls appear to highlight.

It appears that the "Private Identity" and "Secret Key" text entry fields in the "Yubico OTP" tab don't work either, but I didn't play with them as much.  Text entry fields in other tabs work as expected.

I am running a Mac.  I installed Personalization Tool from the App Store today.  From the About tab:

Application Version: 3.1.23
Library Version: 1.17.2

I am running OS X El Capitan, version 10.11.2 (15C50) on a MacBook Pro (Retina, 13-inch, Early 2015).  I have an external monitor, and the same thing happens whether I have the window on the internal display, external display, or if I unplug the external display and re-run on the internal display only.  The computer is new and doesn't have any weird extensions installed.

The YubiKey is a Neo running firmware 3.4.3.

**Comment by peterkaminski** [comment]
Same behavior on a MacBook (13-inch, Late 2009) running OS X Yosemite 10.10.5 (14F1509), with both the Neo and an Edge (firmware 4.1.6).

**Comment by klali** [comment]
To activate the password box in scancode mode you have to select a keyboard layout to the right.

For the OTP quick configuration the boxes are also disabled (though I must confess that I don't really understand why).

**Comment by peterkaminski** [comment]
D'oh!  I played with the keyboard layout selector, but apparently not enough to notice that it enabled the password entry field.  Thanks, that works.

I would still leave this issue open as a ticket to improve the UI.  There could be a label that says "Select keyboard layout, then enter password".

I also didn't find the keyboard layout step in the docs, https://www.yubico.com/wp-content/uploads/2012/10/Cross-Platform-YubiKey-Personalization-Tool-3.0.1-User-guide-v5.pdf , but I see that it's a little old and documents a version without the keyboard layout anyway.

Thanks again for getting me going!

**Comment by SueHeim** [comment]
We'll be updating the Personalization Tool user docs in the not-too-distant future. If you want to open a new issue against the docs, I'll assign it to me (and I'm sure Klas wouldn't mind). I don't have a date yet  but it should be within this quarter as those docs are very outdated! Would that work for you, Peter?
