### ISSUE TITLE
Support for Dvorak

### ISSUE THREAD

**Issue by mkotsbak** [Yubico/yubikey-personalization-gui#7]
When using Dvorak keyboard layout, the generated keys do not work.

It is probably not so easy to support, but one idea I have is to be able to select Dvorak in the configuration. Then it could either always be used with Dvorak, or you could have one config with Dvorak and one with Qwerty.

**Comment by lindes** [comment]
Just a comment: I found this to work for me on MacOS X:

http://superuser.do/yubikey-support-for-non-qwerty-keyboard-layouts-on-mac-os-x/

**Comment by ilmaisin** [comment]
Would it be possible to just send all modhex scancodes in a predefined order, so the authentication server could calibrate itself to support pretty much any layout? Have I understood something wrong about the operation principle of Yubikey?

**Comment by klali** [comment]
It is possible to send the modhex alphabet first (set the configuration flag send-ref) though no server/client combo that I know of has support for this. There's also https://bitbucket.org/dholth/yubikey/src which can be implemented in clients to transcode the input to standard modhex.

**Comment by Kiran-Rao** [comment]
@lindes Broken link:
https://superuser.do/2014/10/22/yubikey-support-for-non-qwerty-keyboard-layouts-on-mac-os-x/
