### ISSUE TITLE
Yubikey Personalization Version 3.1.24 crashes on Sierra (macOS)

### ISSUE THREAD

**Issue by gyoza** [Yubico/yubikey-personalization-gui#70]
Unfortunately I cannot paste the crash log as it wont let me copy it...

**Comment by SueHeim** [comment]
Version 3.1.24 of this tool was built in January, before macOS Sierra was available for preview. I'm not certain, but I believe the next release (3.1.25) may provide support for this new version of the OS. Unfortunately, when Apple releases new versions of their operating systems, existing tools sometimes break. Thanks for letting us know!

**Comment by gyoza** [comment]
Right, wasn't saying that it should work.. Rather, I expected it not to work.. Do you guys have a team working on a beta yet? Release is around the corner, people will adopt quickly...

**Comment by SueHeim** [comment]
I'm not certain who's working on what -- although I know the new version of the OS is on our radar, and reminds me we need to be sure all our key tools work with macOS Sierra when it comes out. You're right about fast adoption... Mac users tend to adopt very quickly when there is a new release.

Thanks for testing and letting us know. I don't know if anyone internally has tested and/or reported around yet, so this helps me a lot.

**Comment by gyoza** [comment]
Woot :) No problem!

**Comment by a-dma** [comment]
I tried replicating this but to no avail. Could you please give some more info?

Specifically:
- when does it crash? As soon as you do anything or after a specific operation?
- what version of the OS are you running? Output of `sw_vers` would be nice. Keep in mind that there has been an update from Apple. Try installing that if you haven't already.
- What are the kind and version of your YubiKey? What mode is it in?

**Comment by gyoza** [comment]
So crazy thing, I've rebooted since and just attempted to reproduce the issue and it is now working.. *sigh* computers. :)

however, 

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A238m

yubikey nano, and first time i've plugged it in... Setup as a keyboard? Not sure:P

**Comment by a-dma** [comment]
Ah, the magic of a reboot.

I've tested on the same OS version and I was never able to replicate.
I'm closing the issue for now, but please feel free to reopen it if the problem resurfaces.
