### ISSUE TITLE
YubiKey 4 Static Password Scan Code is 00 for many keys on macOS

### ISSUE THREAD

**Issue by theq86** [Yubico/yubikey-personalization-gui#81]
Hey,

When I have a password containing brackets or curly braces { or [ on German keyboard layout, they are all evaluated to scan code 00, which leads to this char being ommited in the YK output.

However, when I change to US keyboard layout, the key codes are read correctly.

But I need this password exactly as I would type it with german layout.

App Version:  3.1.24
Lib Version: 1.17.3
OS: macOS 10.13.5 High Sierra
Device: MacBookPro14,2 (13 inch 2017 with TouchBar)

**Comment by klali** [comment]
Unfortunately the YubiKey doesn't support anything but shift as a modifier for scancode strings, those characters need that on a german keyboard IIRC.

If there are keys that can be constructed without a modifier that don't appear correctly that needs to be fixed though.
