### ISSUE TITLE
Can't compile - Project ERROR: Package ykpers-1 not found

### ISSUE THREAD

**Issue by tux1980** [Yubico/yubikey-personalization-gui#93]
System: Fedora 30 

Hi guys,

While compiling (qmake && make), I get always the following output:
Project MESSAGE: Release build
Project MESSAGE: Unix build
sh: 1: pkg-config: not found
Project ERROR: Package ykpers-1 not found
Makefile:69: recipe for target 'src//Makefile' failed
make: *** [src//Makefile] Error 2

The packages have been installed as instructed.

Any Ideas?
Thanks!

**Comment by klali** [comment]
You need to have pkg-config installed for finding the dependencies.

(and you might want to look at yubikey-manager rather than this).
